studio:
  _attributes:    { package: plugins.appFlowerStudioPlugin.lib.model }

  afs_notification: 
    _attributes: { phpName: afsNotification }
    message: { type: VARCHAR, size: 255, required: true }
    message_type: { type: VARCHAR, size: 255, required: true }
    user: { type: VARCHAR, size: 128, required: true }
    ip: { type: VARCHAR, size: 255, required: true }
    created_at: